### ISSUE TITLE
Why the iOS8+ limitation?

### ISSUE THREAD

**Issue by thedp** [zhxnlai/ZLPeoplePickerViewController#1]
I've tried the demo project on a real iPhone 4 with iOS7.1.2, and it seems to work OK.
Is there any specific reason why you decided it's iOS8+ ?

Thanks.

**Comment by zhxnlai** [comment]
ZLPeoplePickerViewController uses [UISearchController](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UISearchController/index.html)(which is available since iOS 8) for displaying search results. Does the search bar work on your device?

**Comment by thedp** [comment]
As you can see in the attached screenshots, the search bar is simply missing in iOS7 simulator and the real device:
![screen shot 2015-04-16 at 1 08 39 am](https://cloud.githubusercontent.com/assets/4397943/7170282/55e5f02a-e3d5-11e4-9cc1-dde9e53ebaba.png)
![screen shot 2015-04-16 at 1 08 57 am](https://cloud.githubusercontent.com/assets/4397943/7170283/55e72f94-e3d5-11e4-959e-3f5e78435a4e.png)

**Comment by zhxnlai** [comment]
Thanks for your feedback!
