### ISSUE TITLE
How can i set ZLPeoplePickerViewController as Initial ViewController for navigation controller?

### ISSUE THREAD

**Issue by ismaiI1** [zhxnlai/ZLPeoplePickerViewController#15]
i have 5 tabs and navigation bar. i want to add this project to my third tab. 

[self.navigationController pushViewController:self.peoplePicker animated:YES];

when i add like that, back button shown on navigation bar. 

i mean, i want to like that 
![whatsapp](https://cloud.githubusercontent.com/assets/8086679/9809561/152e1fc8-5872-11e5-96fe-dc5fbd59983f.png)

how can i do that? and sorry for my english.

**Comment by lteti77** [comment]
i think you should simply declare a navigation controller, initialize the root viewcontroller with ZLPeoplePickerViewController and set the third tab with the navigation controller.

```
UITabBarController *tbc = [[UITabBarController alloc] init];
UINavigationController *nc = [[UINavigationController alloc] initWithRootViewController:self.peoplePicker];
NSArray *controllers = [NSArray arrayWithObjects: /*first, second*/ nc /*fourth, fifth*/,nil];
tbc.viewControllers = controllers;
```

**Comment by ismaiI1** [comment]
too late :) .. i made my own people picker. thanks 👍
